
NameplateAurasDB = {
}
NameplateAurasAceDB = {
	["profileKeys"] = {
		-- WoW #2
		["Aêthyz - Elune"] = "Default",
		-- WoW #3
		["Aëthÿs - Elune"] = "Default",
		["Äethÿs - Elune"] = "Default",
		["Aethysa - Elune"] = "Default",
		["Aëthyz - Elune"] = "Default",
		-- WoW #4
		["Aèthÿs - Elune"] = "Default",
		["Aethykz - Elune"] = "Default",
		-- WoW #5
		["Aethypz - Elune"] = "Default",
		["Aèthÿz - Elune"] = "Default",
		-- WoW #6
		["Aethyst - Elune"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["HideBlizzardFrames"] = false,
			["DefaultSpellsAreImported"] = true,
			["ShowAurasOnPlayerNameplate"] = true,
			["DefaultIconSize"] = 25,
			["FontScale"] = 0.8,
			["IconYOffset"] = 45,
			["TimerTextAnchorIcon"] = "CENTER",
			["StacksTextAnchorIcon"] = "BOTTOMRIGHT",
			["StacksTextXOffset"] = 0,
			["StacksTextYOffset"] = 3,
			["CustomSpells2"] = {
				--- Emerald Nightmare
				-- Nythendra
				[203097] = { -- Rot
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 203097,
				},
				[204470] = { -- Volatile Rot
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 204470,
				},
				--- Trial of Valor
				-- Guarm
				[227539] = { -- Fiery Phlegm
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227539,
				},
				[227566] = { -- Salty Spittle
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227566,
				},
				[227570] = { -- Dark Discharge
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227570,
				},
				[228744] = { -- Flaming Volatile Foam
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228744,
				},
				[228810] = { -- Briney Volatile Foam
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228810,
				},
				[228818] = { -- Shadowy Volatile Foam
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228818,
				},
				-- Helya
				[193367] = { -- Fetid Rot
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 193367,
				},
				[227903] = { -- Orb of Corruption
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227903,
				},
				[228054] = { -- Taint of the Sea
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228054,
				},
				[228058] = { -- Orb of Corrosion
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228058,
				},
				[232450] = { -- Corrupted Axion
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 232450,
				},
                ----
                --- From Default
                ----
                [871] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 871,
				},
				[88611] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 88611,
				},
				[221527] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 221527,
				},
				[31935] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31935,
				},
				[140023] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 140023,
				},
				[51271] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 51271,
				},
				[200108] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 200108,
				},
				[33206] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 33206,
				},
				[29166] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 29166,
				},
				[118] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 118,
				},
				[104773] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 104773,
				},
				[110909] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 110909,
				},
				[1044] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 1044,
				},
				[61336] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 61336,
				},
				[205369] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 205369,
				},
				[122783] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 122783,
				},
				[130736] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 130736,
				},
				[20066] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 20066,
				},
				[125174] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 125174,
				},
				[212638] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 212638,
				},
				[216113] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 216113,
				},
				[34976] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 34976,
				},
				[408] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 408,
				},
				[2094] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 2094,
				},
				[108839] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 108839,
				},
				[152173] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 152173,
				},
				[212640] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 212640,
				},
				[137639] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 137639,
				},
				[53480] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 53480,
				},
				[196098] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 196098,
				},
				[31661] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31661,
				},
				[117526] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 117526,
				},
				[5211] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 5211,
				},
				[48707] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 48707,
				},
				[74001] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 74001,
				},
				[114052] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 114052,
				},
				[99] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 99,
				},
				[22812] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 22812,
				},
				[5484] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 5484,
				},
				[12472] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 12472,
				},
				[120954] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 120954,
				},
				[6770] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 6770,
				},
				[198589] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 198589,
				},
				[211881] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 211881,
				},
				[30283] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 30283,
				},
				[31821] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31821,
				},
				[23920] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 23920,
				},
				[194223] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 194223,
				},
				[47481] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 47481,
				},
				[122278] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 122278,
				},
				[6789] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 6789,
				},
				[1833] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 1833,
				},
				[19386] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 19386,
				},
				[47585] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 47585,
				},
				[9484] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 9484,
				},
				[207167] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 207167,
				},
				[12042] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 12042,
				},
				[86659] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 86659,
				},
				[51514] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 51514,
				},
				[5277] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 5277,
				},
				[221703] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 221703,
				},
				[102342] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 102342,
				},
				[47482] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 47482,
				},
				[78675] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 78675,
				},
				[108271] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 108271,
				},
				[1776] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 1776,
				},
				[1330] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 1330,
				},
				[196555] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 196555,
				},
				[197862] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 197862,
				},
				[115268] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 115268,
				},
				[124974] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 124974,
				},
				[19263] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 19263,
				},
				[54216] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 54216,
				},
				[51690] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 51690,
				},
				[31230] = {
					["enabledState"] = "all",
					["auraType"] = "buff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31230,
				},
				[6940] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 6940,
				},
				[171152] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 171152,
				},
				[228049] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 228049,
				},
				[194249] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 194249,
				},
				[122] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 122,
				},
				[3355] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 3355,
				},
				[207319] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 207319,
				},
				[45438] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 45438,
				},
				[69369] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 69369,
				},
				[3045] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 3045,
				},
				[108416] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 108416,
				},
				[198817] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 198817,
				},
				[115078] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 115078,
				},
				[199804] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 199804,
				},
				[1719] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 1719,
				},
				[207810] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 207810,
				},
				[113724] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 113724,
				},
				[8122] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 8122,
				},
				[22570] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 22570,
				},
				[196718] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 196718,
				},
				[105771] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 105771,
				},
				[16166] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 16166,
				},
				[136634] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 136634,
				},
				[87204] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 87204,
				},
				[199683] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 199683,
				},
				[31117] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31117,
				},
				[37506] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 37506,
				},
				[8178] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 8178,
				},
				[108194] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 108194,
				},
				[5246] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 5246,
				},
				[105421] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 105421,
				},
				[132168] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 132168,
				},
				[132169] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 132169,
				},
				[102359] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 102359,
				},
				[33395] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 33395,
				},
				[186265] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 186265,
				},
				[31224] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31224,
				},
				[209789] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 209789,
				},
				[6358] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 6358,
				},
				[210918] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 210918,
				},
				[853] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 853,
				},
				[198111] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 198111,
				},
				[197871] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 197871,
				},
				[642] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 642,
				},
				[118905] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 118905,
				},
				[121471] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 121471,
				},
				[116849] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 116849,
				},
				[152151] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 152151,
				},
				[204150] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 204150,
				},
				[46924] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 46924,
				},
				[115176] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 115176,
				},
				[118038] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 118038,
				},
				[163505] = {
					["showOnEnemies"] = true,
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["checkSpellID"] = 163505,
					["showOnFriends"] = true,
					["spellID"] = 163505,
				},
				[107574] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 107574,
				},
				[15487] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 15487,
				},
				[33786] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 33786,
				},
				[31850] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31850,
				},
				[47476] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 47476,
				},
				[18499] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 18499,
				},
				[135373] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 135373,
				},
				[339] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 339,
				},
				[13750] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 13750,
				},
				[205191] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 205191,
				},
				[200166] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 200166,
				},
				[15286] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 15286,
				},
				[89766] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 89766,
				},
				[198144] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 198144,
				},
				[224668] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 224668,
				},
				[5782] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 5782,
				},
				[119381] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 119381,
				},
				[120086] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 120086,
				},
				[212295] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 212295,
				},
				[7922] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 7922,
				},
				[188501] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 188501,
				},
				[605] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 605,
				},
				[1022] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 1022,
				},
				[23335] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 23335,
				},
				[710] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 710,
				},
				[23333] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 23333,
				},
				[2825] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 2825,
				},
				[200200] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 200200,
				},
				[31842] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 31842,
				},
				[48792] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 48792,
				},
				[64695] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 64695,
				},
				[47788] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 47788,
				},
				[179057] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 179057,
				},
				[10060] = {
					["enabledState"] = "all",
					["auraType"] = "buff/debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = true,
					["showOnFriends"] = true,
					["spellID"] = 10060,
				},
			},
		},
		["EN & ToV"] = {
			["HideBlizzardFrames"] = false,
			["DefaultSpellsAreImported"] = true,
			["ShowAurasOnPlayerNameplate"] = true,
			["DefaultIconSize"] = 25,
			["FontScale"] = 0.8,
			["IconYOffset"] = 45,
			["TimerTextAnchorIcon"] = "CENTER",
			["StacksTextAnchorIcon"] = "BOTTOMRIGHT",
			["StacksTextXOffset"] = 0,
			["StacksTextYOffset"] = 3,
			["CustomSpells2"] = {
				--- Emerald Nightmare
				-- Nythendra
				[203097] = { -- Rot
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 203097,
				},
				[204470] = { -- Volatile Rot
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 204470,
				},
				--- Trial of Valor
				-- Guarm
				[227539] = { -- Fiery Phlegm
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227539,
				},
				[227566] = { -- Salty Spittle
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227566,
				},
				[227570] = { -- Dark Discharge
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227570,
				},
				[228744] = { -- Flaming Volatile Foam
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228744,
				},
				[228810] = { -- Briney Volatile Foam
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228810,
				},
				[228818] = { -- Shadowy Volatile Foam
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228818,
				},
				-- Helya
				[193367] = { -- Fetid Rot
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 193367,
				},
				[227903] = { -- Orb of Corruption
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 227903,
				},
				[228054] = { -- Taint of the Sea
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228054,
				},
				[228058] = { -- Orb of Corrosion
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 228058,
				},
				[232450] = { -- Corrupted Axion
					["enabledState"] = "all",
					["auraType"] = "debuff",
					["iconSize"] = 25,
					["showOnEnemies"] = false,
					["showOnFriends"] = true,
					["spellID"] = 232450,
				}
			},
		},
	},
}
